# Generated by Django 5.2.3 on 2025-07-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvprofile",
            name="skin",
            field=models.CharField(
                choices=[
                    ("default", "Clásico"),
                    ("modern", "Moderno"),
                    ("minimal", "Minimalista"),
                ],
                default="default",
                max_length=50,
            ),
        ),
    ]
