# Generated by Django 5.2.3 on 2025-07-14 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_cvprofile_skin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="cvprofile",
            old_name="educations",
            new_name="selected_educations",
        ),
        migrations.RenameField(
            model_name="cvprofile",
            old_name="experiences",
            new_name="selected_experiences",
        ),
        migrations.RenameField(
            model_name="cvprofile",
            old_name="hobbies",
            new_name="selected_hobbies",
        ),
        migrations.RenameField(
            model_name="cvprofile",
            old_name="languages",
            new_name="selected_languages",
        ),
        migrations.RenameField(
            model_name="cvprofile",
            old_name="softskills",
            new_name="selected_softskills",
        ),
        migrations.AlterField(
            model_name="cvprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cv_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
