# Generated by Django 5.2.3 on 2025-07-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_rename_educations_cvprofile_selected_educations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("premium", "Premium"),
                    ("admin", "Admin"),
                    ("teacher", "Teacher"),
                    ("headhunter", "Headhunter"),
                    ("professional", "Professional"),
                ],
                default="user",
                max_length=100,
            ),
        ),
    ]
