# Generated by Django 5.2.3 on 2025-07-16 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_userprofile_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlanguage",
            name="level",
            field=models.CharField(
                choices=[
                    ("A1", "A1 – Beginner"),
                    ("A2", "A2 – Elementary"),
                    ("B1", "B1 – Intermediate"),
                    ("B2", "B2 – Upper‑intermediate"),
                    ("C1", "C1 – Advanced"),
                    ("C2", "C2 – Proficient"),
                    ("N", "Native"),
                ],
                max_length=2,
                verbose_name="Nivel",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userlanguage",
            unique_together={("user", "language")},
        ),
    ]
