# Generated by Django 5.2.3 on 2025-07-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_userlanguage_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvprofile",
            name="font_family",
            field=models.CharField(default="sans-serif", max_length=50),
        ),
        migrations.AddField(
            model_name="cvprofile",
            name="header_image",
            field=models.ImageField(blank=True, null=True, upload_to="cv_headers/"),
        ),
        migrations.AddField(
            model_name="cvprofile",
            name="primary_color",
            field=models.CharField(default="#000000", max_length=20),
        ),
    ]
