# Generated by Django 5.2.3 on 2025-07-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_cvprofile_font_family_cvprofile_header_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
