# Generated by Django 5.2.4 on 2025-09-18 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('title', models.CharField(max_length=200, verbose_name='Título del puesto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Ubicación')),
                ('modality', models.CharField(choices=[('remote', 'Remoto'), ('onsite', 'Presencial'), ('hybrid', 'Híbrido')], default='onsite', max_length=20, verbose_name='Modalidad')),
                ('salary', models.CharField(blank=True, max_length=100, verbose_name='Salario')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoría')),
                ('requirements', models.TextField(blank=True, verbose_name='Requisitos')),
                ('benefits', models.TextField(blank=True, verbose_name='Beneficios')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers_created', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Oferta de Empleo',
                'verbose_name_plural': 'Ofertas de Empleo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('mensaje_personalizado', models.TextField(blank=True, null=True, verbose_name='Mensaje personalizado')),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de aplicación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_applications', to=settings.AUTH_USER_MODEL, verbose_name='Candidato')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.joboffer', verbose_name='Oferta de Empleo')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
                'ordering': ['-fecha_aplicacion'],
                'unique_together': {('offer', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AgendaAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título de la acción')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_hora_inicio', models.DateTimeField(verbose_name='Fecha y Hora de Inicio')),
                ('duracion_minutos', models.PositiveIntegerField(default=30, verbose_name='Duración (minutos)')),
                ('tipo', models.CharField(choices=[('entrevista', 'Entrevista'), ('llamada', 'Llamada'), ('recordatorio', 'Recordatorio'), ('entrega', 'Entrega'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo de acción')),
                ('finished', models.BooleanField(default=False, verbose_name='Finalizada')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_acciones', to=settings.AUTH_USER_MODEL, verbose_name='Realizada por')),
                ('candidatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_agendadas_candidatura', to='jobs.candidatura', verbose_name='Candidatura asociada')),
                ('oferta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_agendadas', to='jobs.joboffer', verbose_name='Oferta asociada')),
            ],
            options={
                'verbose_name': 'Acción de Agenda',
                'verbose_name_plural': 'Acciones de Agenda',
                'ordering': ['fecha_hora_inicio'],
                'indexes': [models.Index(fields=['user'], name='jobs_agenda_user_id_c4903d_idx'), models.Index(fields=['fecha_hora_inicio'], name='jobs_agenda_fecha_h_8d5c13_idx'), models.Index(fields=['oferta'], name='jobs_agenda_oferta__ffd9c5_idx'), models.Index(fields=['candidatura'], name='jobs_agenda_candida_74da17_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatusMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado de Candidatura')),
                ('mensaje', models.TextField(verbose_name='Plantilla de Mensaje')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_templates', to=settings.AUTH_USER_MODEL, verbose_name='Usuario (Headhunter)')),
            ],
            options={
                'verbose_name': 'Plantilla de Mensaje de Estado',
                'verbose_name_plural': 'Plantillas de Mensajes de Estado',
                'unique_together': {('user', 'estado')},
            },
        ),
    ]
