# Generated by Django 5.2.4 on 2025-07-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="joboffer",
            name="benefits",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="requirements",
            field=models.TextField(blank=True),
        ),
    ]
