# Generated by Django 5.2.4 on 2025-07-16 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_joboffer_headhunter_candidature"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccionOferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("llamada", "Llamada"),
                            ("entrevista", "Entrevista"),
                            ("nota", "Nota Interna"),
                            ("seguimiento", "Seguimiento"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "oferta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acciones",
                        to="jobs.joboffer",
                    ),
                ),
                (
                    "realizada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Oferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                (
                    "empresa",
                    models.CharField(
                        help_text="Nombre de la empresa asociada", max_length=255
                    ),
                ),
                ("descripcion", models.TextField()),
                ("fecha_publicacion", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ofertas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgendaAccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                ("duracion_minutos", models.PositiveIntegerField(default=30)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "oferta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acciones",
                        to="jobs.oferta",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="oferta",
            index=models.Index(fields=["user"], name="jobs_oferta_user_id_48034f_idx"),
        ),
        migrations.AddIndex(
            model_name="oferta",
            index=models.Index(
                fields=["fecha_publicacion"], name="jobs_oferta_fecha_p_18f7b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agendaaccion",
            index=models.Index(fields=["user"], name="jobs_agenda_user_id_c4903d_idx"),
        ),
        migrations.AddIndex(
            model_name="agendaaccion",
            index=models.Index(fields=["fecha"], name="jobs_agenda_fecha_71dd74_idx"),
        ),
        migrations.AddIndex(
            model_name="agendaaccion",
            index=models.Index(
                fields=["oferta"], name="jobs_agenda_oferta__ffd9c5_idx"
            ),
        ),
    ]
