# Generated by Django 5.2.4 on 2025-09-18 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoInteligencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(max_length=255)),
                ('aciertos', models.IntegerField()),
                ('fallos', models.IntegerField()),
                ('total', models.IntegerField()),
                ('resultados', models.JSONField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(max_length=255)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('aciertos', models.IntegerField()),
                ('fallos', models.IntegerField()),
                ('total_preguntas', models.IntegerField()),
                ('detalle', models.JSONField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaRespondida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('respuestas_correctas', models.JSONField()),
                ('respuestas_usuario', models.JSONField()),
                ('es_correcta', models.BooleanField()),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_test.resultadotest')),
            ],
        ),
        migrations.CreateModel(
            name='ComentariosProfessores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('comentario_usuario', models.TextField(blank=True, null=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management_test.resultadotest')),
            ],
        ),
    ]
