# Generated by Django 5.2.3 on 2025-07-08 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectoresProfesionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('Legal', 'Legal'), ('Salud', 'Salud'), ('Educación', 'Educación'), ('Finanzas', 'Finanzas'), ('Gestión', 'Gestión'), ('Programación', 'Programación'), ('Marketing', 'Marketing'), ('Otro', 'Otro')], default='Otro', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('email2', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.sectoresprofesionales')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('date_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
                ('user_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('professional_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.profesional')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.sectoresprofesionales')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('date_at', models.DateTimeField(auto_now_add=True)),
                ('professional_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.profesional')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.pregunta')),
                ('user_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
