# Generated by Django 5.2.4 on 2025-07-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='sector',
            field=models.CharField(choices=[('Legal', 'Legal'), ('Salud', 'Salud'), ('Educación', 'Educación'), ('Finanzas', 'Finanzas'), ('Gestión', 'Gestión'), ('Programación', 'Programación'), ('Marketing', 'Marketing'), ('Otro', 'Otro')], default='Otro', max_length=50),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='sector',
            field=models.CharField(choices=[('Legal', 'Legal'), ('Salud', 'Salud'), ('Educación', 'Educación'), ('Finanzas', 'Finanzas'), ('Gestión', 'Gestión'), ('Programación', 'Programación'), ('Marketing', 'Marketing'), ('Otro', 'Otro')], default='Otro', max_length=50),
        ),
        migrations.DeleteModel(
            name='SectoresProfesionales',
        ),
    ]
