# Generated by Django 5.2.4 on 2025-07-14 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_pregunta_sector_alter_profesional_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='professional_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.profesional'),
        ),
    ]
