# Generated by Django 5.2.4 on 2025-07-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_pregunta_professional_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='titulo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
