# Generated by Django 5.2.4 on 2025-07-14 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_pregunta_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='professional_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.profesional'),
        ),
    ]
