# Generated by Django 5.2.3 on 2025-07-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_respuesta_professional_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='active_until',
            field=models.DateTimeField(null=True),
        ),
    ]
