# Generated by Django 5.2.4 on 2025-07-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_respuesta_professional_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
