# Generated by Django 5.2.4 on 2025-07-17 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_respuesta_professional_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.sector'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.sector'),
        ),
    ]
