# Generated by Django 5.2.4 on 2025-07-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_sector_alter_pregunta_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='nombre',
            field=models.CharField(default='Otro', max_length=50, unique=True),
        ),
    ]
