# Generated by Django 5.2.3 on 2025-07-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_pregunta_active_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
