# Generated by Django 5.2.4 on 2025-07-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_pregunta_edited'),
        ('forum', '0007_alter_sector_nombre'),
    ]

    operations = [
    ]
