# Generated by Django 5.2.4 on 2025-07-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_merge_0006_pregunta_edited_0007_alter_sector_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='pregunta',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sector',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
