# Generated by Django 5.2.3 on 2025-07-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_pregunta_active_until'),
        ('forum', '0009_alter_pregunta_pregunta_alter_sector_nombre'),
    ]

    operations = [
    ]
