# Generated by Django 5.2.3 on 2025-07-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_create_initial_sectors'),
        ('forum', '0010_merge_20250722_1131'),
    ]

    operations = [
    ]
