# Generated by Django 5.2.4 on 2025-07-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_merge_20250722_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='editado',
            field=models.BooleanField(default=False),
        ),
    ]
