# Generated by Django 5.2.4 on 2025-07-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_merge_20250722_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='nombre',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
