# Generated by Django 5.2.4 on 2025-07-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_respuesta_editado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='editado',
        ),
    ]
