# Generated by Django 5.2.4 on 2025-07-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_remove_respuesta_editado'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='editado',
            field=models.BooleanField(default=False),
        ),
    ]
