# Generated by Django 5.2.4 on 2025-07-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_profesional_nombre'),
        ('forum', '0014_respuesta_editado'),
    ]

    operations = [
    ]
