# Generated by Django 5.2.4 on 2025-07-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_merge_0012_profesional_nombre_0014_respuesta_editado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='editado',
        ),
    ]
