# Generated by Django 5.2.4 on 2025-07-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_remove_respuesta_editado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='active_until',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
