# Generated by Django 5.2.4 on 2025-07-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_alter_pregunta_active_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
