# Generated by Django 5.2.4 on 2025-10-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvprofile",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
