# Generated by Django 5.2.4 on 2025-09-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_manager", "0002_hardskill_userhardskill"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhobby",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
