# Generated by Django 5.2.4 on 2025-09-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_manager", "0003_userhobby_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvprofile",
            name="selected_hardskills",
            field=models.ManyToManyField(blank=True, to="cv_manager.userhardskill"),
        ),
    ]
